backend/controllers/CacheController.php
<?php
/**
 * Desc: 缓存管理
 * Created by PhpStorm.
 * User: xstnet
 * Date: 19-07-26
 * Time: 下午12:56
 */

namespace backend\controllers;

use common\exceptions\ParameterException;
use common\models\AdminUser;
use yii\filters\VerbFilter;
use Yii;

class CacheController extends AdminLogController
{
	public function behaviors()
	{
		return array_merge(
			parent::behaviors(),
			[
				'verbs' => [
					'class' => VerbFilter::className(),
					'actions' => [
						'index' => ['get'],
						'clear-index' => ['get'],
						'clear-all' => ['get'],
					],
				],
			]
		);
	}

	public function actions()
	{
		return [

		];
	}

	/**
	 * @Desc: 个人信息，页面
	 * @return string
	 */
	public function actionIndex()
	{

		return $this->render('index', [
		]);
	}
	
	/**
	 * 清理首页缓存
	 * @return array
	 */
	public function actionClearIndex()
	{
		Yii::$app->userCache->refresh('setting');
		Yii::$app->userCache->refresh('articleCategory');
		Yii::$app->userCache->refresh('ArticleCategoryTree');
		Yii::$app->userCache->refresh('latestArticle');
		Yii::$app->userCache->refresh('tagList');
		
		$this->renderIndex();
		
		return self::ajaxSuccess('清理成功');
	}
	
	/**
	 * 清理全部缓存
	 * @return array
	 */
	public function actionClearAll()
	{
		//Yii::$app->cache->useDefault();
		Yii::$app->cache->flush();
		
		$dir = Yii::getAlias('@backend/runtime/cache');
		if (is_dir($dir)) {
			$this->removeDir($dir);
		}
		
		$this->renderIndex();
		
		return self::ajaxSuccess('清理成功');
	}

	private function renderIndex()
	{
		return true;
		$url = 'https://www.xstnet.com/index.php';
		if (YII_ENV == 'dev') {
			$url = 'http://yii-admin.com/index.php';
		}
		
		$arrContextOptions = [
			"ssl"=> [
				"verify_peer" => false,
				"verify_peer_name" => false,
			],
		];
		
		$indexHtml = file_get_contents($url, false, stream_context_create($arrContextOptions));
		$filepath = Yii::getAlias('@frontend/web/index.html');
		file_put_contents($filepath, $indexHtml);
	}
	
	public function removeDir($dirName)
	{
		if(!is_dir($dirName))
		{
			return false;
		}
		$handle = @opendir($dirName);
		while(($file = @readdir($handle)) !== false)
		{
			//判断是不是文件 .表示当前文件夹 ..表示上级文件夹 =2
			if($file != '.' && $file != '..')
			{
				$dir = $dirName . '/' . $file;
				is_dir($dir) ? $this->removeDir($dir) : @unlink($dir);
			}
		}
		closedir($handle);
		@rmdir($dirName);
	}

}

backend/views/cache/index.php
<?php
/**
 * Desc:
 * Created by PhpStorm.
 * User: xstnet
 * Date: 18-10-22
 * Time: 下午3:51
 */

/* @var $this yii\web\View */

use yii\helpers\Html;
?>
<?php $this->beginPage() ?>
	<!DOCTYPE html>
	<html lang="zh-CN">
	<head>
		<title>缓存管理</title>
		<?= $this->render('../public/header.php')?>
		<?php $this->head() ?>
		<style>
			#headImg {
				width: 120px;
				height: 120px;
			}
			.layui-disabled {
				background-color: #e4e4e4;
				color: #040404 !important;
			}
			body {
				background-color: #F2F2F2;
			}
		</style>
	</head>
	<?php $this->beginBody() ?>
	<body class="body">

	<span id="csrfToken"><?=Yii::$app->request->csrfToken?></span>

	<div style="padding-left: 20px; margin-top: 20px">
		
		<div class="layui-btn-container">
			<button type="button" data-href="<?=Yii::$app->urlManager->createUrl('cache/clear-index')?>" class="layui-btn clear-cache">清除首页缓存</button>
			<button type="button" data-href="<?=Yii::$app->urlManager->createUrl('cache/clear-all')?>" class="layui-btn clear-cache">清除全部</button>
		</div>
	
	</div>




	<?= $this->render('../public/footer_js.php')?>
	<?= Html::jsFile('@static_backend/js/index.js')?>

	<script type="text/javascript">
		// layui方法
		layui.use(['layer',], function () {
			// 操作对象
			var form = layui.form
				, layer = layui.layer
				, $ = layui.jquery
				;
			
			// 清理缓存
			$('.clear-cache').click(function () {
				let url = $(this).data('href');
				$.getJSON(
					url,
					{},
					function (result) {
						layer.msg(result.message);
					}
				)
			})

		});
	</script>
	<?php $this->endBody() ?>
	</body>
	</html>
<?php $this->endPage() ?>