backend/controllers/ArticleController.php
<?php
/**
 * 文章管理
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/10/27
 * Time: 13:46
 */

namespace backend\controllers;


use backend\services\article\ArticleService;
use common\helpers\Helpers;
use common\models\Article;
use common\models\ArticleComment;
use yii\filters\VerbFilter;
use Yii;

class ArticleController extends AdminLogController
{
	public function behaviors()
	{
		return array_merge(
			parent::behaviors(),
			[
				'verbs' => [
					'class' => VerbFilter::className(),
					'actions' => [
						'index' => ['get'],
						'category' => ['get'],
						'add' => ['get'],
						'edit' => ['get'],
						'add-article' => ['post'],
						'get-articles' => ['get'],
						'save-article' => ['post'],
						'save-article-brief' => ['post'],
						'delete-article' => ['post'],
						'delete-articles' => ['post'],
						'add-categoy' => ['post'],
						'save-categoy' => ['post'],
						'save-categoy' => ['post'],
						'get-categories' => ['get'],
						'tags' => ['get'],
						'get-tags' => ['get'],
						'change-tag-status' => ['post'],
						'delete-tags' => ['post'],
						'add-tags' => ['post'],
						'comment' => ['get'],
					],
				],
			]
		);
	}

	/**
	 * 打开文章管理页面
	 */
	public function actionIndex()
	{
		$categories  = ArticleService::instance()->getCategoryList();
		$treeSelect = Helpers::getTreeSelect($categories);
		return $this->render('index', [
			'treeSelect' => $treeSelect,
			'searchFields' => Article::getSearchFieldByAction('index'),
		]);
	}

	/**
	 * 发布文章 页面
	 * @return string
	 */
	public function actionAdd()
	{
		$categories  = ArticleService::instance()->getCategoryList();
		$treeSelect = Helpers::getTreeSelect($categories);
		$type = Yii::$app->request->get('type', 'markdown');
		$view = 'add';
		if ($type === 'html') {
			$view = 'add_uedit';
		}
		return $this->render($view, [
			'treeSelect' => $treeSelect,
		]);
	}
	
	/**
	 * 编辑文章 页面
	 * @param $id
	 * @param string $type
	 * @return string
	 * @throws \yii\base\InvalidConfigException
	 */
	public function actionEdit($id, $type ='')
	{
		$model = Article::findOne($id);
		if (empty($model)) {
			self::ajaxReturn('文章不存在');
		}
		$categories  = ArticleService::instance()->getCategoryList();
		$treeSelect = Helpers::getTreeSelect($categories);
		$view = 'edit_html';
		if (!empty($model->content->markdown_content)) {
			$view = 'edit_markdown';
		}
		if (!empty($type)) {
			$view = 'edit_' . $type;
		}
		return $this->render($view, [
			'treeSelect' => $treeSelect,
			'model' => $model,
		]);
	}

	/**
	 * @Desc: 获取文章列表
	 * @return array
	 */
	public function actionGetArticles()
	{
		$result = ArticleService::instance()->getArticeList();
		return self::ajaxSuccess(self::AJAX_MESSAGE_SUCCESS, $result);
	}

	/**
	 * @Desc: 更新文章是否展示
	 * @return array
	 */
	public function actionChangeIsShow()
	{
		$id = self::postParams('id', 0);
		ArticleService::instance()->changeIsShow($id);
		return self::ajaxSuccess('更新成功');
	}

	/**
	 * @Desc: 更新文章是否允许评论
	 * @return array
	 */
	public function actionChangeIsAllowComment()
	{
		$id = self::postParams('id', 0);
		ArticleService::instance()->changeIsAllowComment($id);
		return self::ajaxSuccess('更新成功');
	}

	/**
	 * @Desc: 发布文章
	 * @return array
	 */
	public function actionAddArticle()
	{
		$params = self::postParams();
		ArticleService::instance()->addArtice($params);
		return self::ajaxSuccess('发布成功');
	}

	/**
	 * @Desc: 编辑文章
	 * @return array
	 */
	public function actionSaveArticle()
	{
		$params = self::postParams();
		ArticleService::instance()->saveArtice($params);
		return self::ajaxSuccess('更新成功');
	}

	/**
	 * @Desc: 删除文章
	 * @return array
	 */
	public function actionDeleteArticle()
	{
		$articleId = self::postParams('id', 0);
		ArticleService::instance()->deleteArtice($articleId);
		return self::ajaxSuccess('删除成功');
	}

	/**
	 * @Desc: 删除文章 批量
	 * @return array
	 */
	public function actionDeleteArticles()
	{
		$articleIds = self::postParams('ids', 0);
		ArticleService::instance()->deleteArtices($articleIds);
		return self::ajaxSuccess('删除成功');
	}

	/**
	 * @Desc: 快速编辑 保存
	 * @return array
	 */
	public function actionSaveArticleBrief()
	{
		$params = self::postParams();
		ArticleService::instance()->saveArticeBrief($params);
		return self::ajaxSuccess('更新成功');
	}

	

	/**
	 * @Desc: 获取分类列表 tree
	 * @return array
	 */
	public function actionGetCategories()
	{
		$result = ArticleService::instance()->getCategoryList();
		return self::ajaxSuccess(self::AJAX_MESSAGE_SUCCESS, $result);
	}

	/**
	 * @Desc: 分类管理 页面
	 */
	public function actionCategory()
	{
		$categories  = ArticleService::instance()->getCategoryList();
		$treeSelect = Helpers::getTreeSelect($categories);
		return $this->render('category', [
			'treeSelect' => $treeSelect,
		]);
	}

	/**
	 * @Desc: 添加分类
	 * @return array
	 */
	public function actionAddCategory()
	{
		$params = self::postParams();
		ArticleService::instance()->addCategory($params);
		return self::ajaxSuccess('添加成功');
	}

	/**
	 * @Desc: 更新分类
	 * @return array
	 */
	public function actionSaveCategory()
	{
		$params = self::postParams();
		ArticleService::instance()->saveCategory($params);
		return self::ajaxSuccess('更新成功');
	}

	/**
	 * @Desc: 删除分类
	 * @return array
	 */
	public function actionDeleteCategory()
	{
		$categoryId = self::postParams('id', 0);
		$moveArticle = self::postParams('move_article', 0);
		$deleteArticle = self::postParams('delete_article', 0);
		$moveToCategoryId = self::postParams('move_to_category_id', 0);
		if (($moveArticle + $deleteArticle) !== 1) {
			self::ajaxReturn('参数错误');
		}
		ArticleService::instance()->deleteCategory($categoryId, $moveArticle, $deleteArticle, $moveToCategoryId);
		return self::ajaxSuccess('删除成功');
	}
	
	/********************************************标签管理****************/
	
	/**
	 * Display tags view
	 * @return string
	 */
	public function actionTags()
	{
		return $this->render('tags');
	}
	
	/**
	 * Ajax Get Tag List
	 * @return array
	 * @throws \yii\base\InvalidConfigException
	 */
	public function actionGetTags()
	{
		$result = ArticleService::instance()->getTagList();
		return self::ajaxSuccess(self::AJAX_MESSAGE_SUCCESS, $result);
	}
	
	/**
	 * Ajax Change Tag is show
	 * @return array
	 * @throws \common\exceptions\DatabaseException
	 * @throws \common\exceptions\ParameterException
	 * @throws \yii\base\InvalidConfigException
	 */
	public function actionChangeTagStatus()
	{
		$tagId = self::postParams('id', 0);
		$result = ArticleService::instance()->changeTagIsShow($tagId);
		return self::ajaxSuccess('更新成功');
	}
	
	/**
	 * Ajax Delete Tags
	 * @return array
	 * @throws \common\exceptions\ParameterException
	 * @throws \yii\base\InvalidConfigException
	 */
	public function actionDeleteTags()
	{
		$tagIds = self::postParams('ids', 0);
		ArticleService::instance()->deleteTags($tagIds);
		return self::ajaxSuccess('删除成功');
	}
	
	/**
	 * Add Tag
	 * @return array
	 * @throws \common\exceptions\DatabaseException
	 * @throws \yii\base\InvalidConfigException
	 */
	public function actionAddTag()
	{
		$params = self::postParams();
		ArticleService::instance()->addTag($params);
		return self::ajaxSuccess('添加成功');
	}
	
	public function actionComment()
	{
		return $this->render('comment');
	}
	
	public function actionGetComments()
	{
		$result = ArticleService::instance()->getCommentList();
		return self::ajaxSuccess(self::AJAX_MESSAGE_SUCCESS, $result);
	}
	
	public function actionCommentReadAll()
	{
		$affectedRows = ArticleComment::updateAll(['is_read' => ArticleComment::IS_READ_YES], ['is_read' => ArticleComment::IS_DELETE_NO]);
		if ($affectedRows !== false) {
			return self::ajaxSuccess('操作成功');
		}
		return self::ajaxReturn('操作失败');
	}
	
	public function actionDeleteComments()
	{
		$ids = self::postParams('ids', 0);
		ArticleService::instance()->deleteComments($ids);
		return self::ajaxSuccess('删除成功');
	}
}

frontend/controllers/ArticleController.php
<?php
/**
 *
 * Created by PhpStorm.
 * Author: Xu shantong <shantongxu@qq.com>
 * Date: 19-7-25
 * Time: 下午3:37
 */

namespace frontend\controllers;


use common\exceptions\ParameterException;
use common\helpers\Helpers;
use common\helpers\MyHtml;
use common\models\Article;
use common\models\ArticleComment;
use common\models\TaskMail;
use Yii;
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\web\NotFoundHttpException;

class ArticleController extends BaseController
{
    public $articleTitle;

	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
		return [
			'PageCache' => [
				'class' => '\common\helpers\ArticlePageCache',
				'only' => ['index'],
				'duration' => 3600,
				'enabled' => YII_ENV == 'prod',
				'variations' => [
					Yii::$app->request->isAjax,
					Yii::$app->request->get('page', 1),
					Yii::$app->request->get('id', 0),
					Yii::$app->request->get('debug', 0),
				],
				'dependency' => [
					'class' => 'yii\caching\DbDependency',
					'sql' => "SELECT `updated_at` FROM x_article where id = :id",
					'params' => [
						':id' => ((int) Yii::$app->request->get('id', 0)),
					]
				],
			],
		];
	}
	/**
	 * Displays Article Content.
	 * @param int $id
	 * @return string
	 * @throws NotFoundHttpException
	 * @throws \yii\db\Exception
	 */
	public function actionIndex(int $id)
	{
		$this->layout = 'article-main';
		// 获取评论
		if (Yii::$app->request->isAjax) {
			$page = Yii::$app->request->get('page', 0);
			if ($page > 0) {
				return $this->getComments();
			}
		}
		
		$article = Article::findOne($id);
		if (empty($article)) {
			throw new NotFoundHttpException('该文章不存在');
		}
		
		Yii::$app->db->createCommand()->update(Article::tableName(), ['hits' => $article->hits+1], 'id='.$article->id)->execute();
		
		$breadcrumb = $this->getArticleBreadcrumb($article);
		
		// 上一条数据
		$prevArticle = Article::find()
			->select(['id', 'title'])
			->where(['>', 'created_at', $article->created_at])
            ->andWhere(['is_delete' => Article::IS_DELETE_NO, 'is_show' => Article::IS_SHOW_YES])
            ->limit(1)
            ->orderBy('created_at desc')
			->asArray()
			->one();
		
		// 下一条数据
		$nextArticle = Article::find()
			->select(['id', 'title'])
            ->where(['<', 'created_at', $article->created_at])
            ->andWhere(['is_delete' => Article::IS_DELETE_NO, 'is_show' => Article::IS_SHOW_YES])
			->limit(1)
            ->orderBy('created_at desc')
			->asArray()
			->one();
		
		if (empty($article->content->directory))  {
			$this->layout = 'main';
		}
		
		return $this->render('index', [
			'article' => $article,
			'breadcrumb' => $breadcrumb,
			'prevArticle' => $prevArticle,
			'nextArticle' => $nextArticle,
		]);
		
	}
	
	/**
	 * 发布评论
	 */
	public function actionRelease()
	{
		if (strpos(Yii::$app->request->userIP, '5.188') !== false) {
		    Yii::info("5.188...........");
			exit("<script>alert('发布成功');location.href='/'</script>");
		}
		
		// 验证留言间隔, 1分钟内只能发一次
		$session = Yii::$app->session;
		$session->open();
		$lastPubAt = $session->get('comment_last_pub_at', 0);
		
		if ($lastPubAt > 0 && ($lastPubAt + 60) > time()) {
			exit("<script>alert('1分钟内只能发布一次哦!');history.go(-1)</script>");
		}
		$params = Yii::$app->request->post();

		if (!preg_match("/([\x81-\xfe][\x40-\xfe])/", $params['content'], $match)) {
			exit("<script>alert('内容必须含有汉字！');history.go(-1)</script>");
		}

		$articleId = (int) ($params['article_id'] ?? 0);
		$article = Article::findOne($articleId);
		if (empty($article)) {
			throw new NotFoundHttpException('该文章不存在!');
		}
		if ($article->is_allow_comment == Article::IS_DELETE_NO) {
			exit("<script>alert('该篇文章不支持评论!');history.go(-1)</script>");
		}
		
		$transaction = Yii::$app->db->beginTransaction();
		try {
			$comment = new ArticleComment();
			$comment->article_id = $articleId;
			$comment->avatar = sprintf('/uploads/avatar/%d.jpg', rand(1, 5));
			$comment->nickname = HtmlPurifier::process(trim($params['nickname'] ?? ''));
			$comment->email = HtmlPurifier::process(trim($params['email'] ?? ''));
			$comment->content = trim($params['content'] ?? '');
			if (empty($comment->content)) {
                throw new ParameterException(ParameterException::INVALID, "请输入文章内容!");
            }
			if (mb_strlen($comment->content) < 2) {
                throw new ParameterException(ParameterException::INVALID, "最少输入2个文字!");
            }

			$this->articleTitle = $article->title;
			// 处理评论内容
			$this->processContent($comment);
            $comment->ip = Yii::$app->request->userIP; // set ip
            // 查询是否回复, 有的话就使用同一个头像
            $prevComment =
                ArticleComment::find()
                    ->where([
                            'article_id' => $articleId,
                            'email' => $comment->email,
                            'nickname' => $comment->nickname]
                    )
                    ->one();
            if ($prevComment) {
                $comment->avatar = $prevComment->avatar;
            }
            unset($prevComment);

			if (!$comment->save()) {
				$error = current($comment->getFirstErrors());
				throw new ParameterException(ParameterException::INVALID, $error);
			}
			
			$article->comment_count ++;
            $article->scenario = 'update-comment_count';
            if (!$article->save()) {
                throw new ParameterException(ParameterException::INVALID, '发布失败');
            }

            $transaction->commit();
		} catch (\Exception $e) {
			$transaction->rollBack();
			exit("<script>alert('". htmlspecialchars($e->getMessage()) ."');history.go(-1)</script>");
		}
		
		$session->set('comment_last_pub_at', time());
		
		exit("<script>alert('发布成功');location.href='/article-".$articleId.".html'</script>");
	}
	
	/**
	 * 获取文章评论列表
	 * @return string
	 */
	public function getComments()
	{
		$this->layout = false;
		
		$articleId = (int) Yii::$app->request->get('id', 0);

		$query = ArticleComment::find()->where(['article_id' => $articleId]);
		
		list ($count, $pages) = $this->getPage($query, 200);
		
		$commentList = $query->asArray()
            ->indexBy('id')
			->all();

		$commentTree = Helpers::getTree($commentList, 'reply_comment_id');

		return $this->renderContentFilter($this->render('get-comments', [
			'commentList' => $commentTree,
			'pages' => $pages,
		]));
	}

    /**
     * 处理评论内容
     *
     * @param $comment ArticleComment
     * @throws \common\exceptions\DatabaseException
     */
	public function processContent($comment)
    {
        $comment->content = strip_tags($comment->content,'<br>');
        $comment->content = str_replace(["\n", "<br>", "<br/>"], '[br]', $comment->content);
        $content = $comment->content;

        $replyModel = null;
        // 处理 @
        $isMatched = preg_match('/\[@.*?(?=#\d+])#(\d+)]/m', $content, $matches);
        if ($isMatched) {
            $replacement = '回复 ' . ArticleComment::getCustomTag('$1 : ', 'span', 'replay-to');
            $content = preg_replace('/\[@(.*?(?=#\d+]))#(\d+)]/m', $replacement, $content);

            $replyId = (int) $matches[1];
            $replyModel = ArticleComment::findOne($replyId);
            if (!empty($replyModel)) {
                $comment->reply_comment_id = $replyId;
                $comment->reply_comment_ids = ltrim($replyModel->reply_comment_ids . ',' . $replyId, ',');

                // 如果回复的层级超过最大层级, 使该回复 同被评论的上级
                if (count(explode(',', $replyModel->reply_comment_ids)) >= ArticleComment::MAX_REPLY_LEVEL) {
                    $comment->reply_comment_id = $replyModel->reply_comment_id;
                } else {
                    // 查询上层中是否有自已的回复, 有的话就在本级
                    if ($replyModel->reply_comment_ids != '') {
                        $hasComment =
                            ArticleComment::find()
                                ->where([
                                        'id' => explode(',', $replyModel->reply_comment_ids),
                                        'email' => $comment->email,
                                        'nickname' => $comment->nickname]
                                )
                                ->exists();
                        if ($hasComment) {
                            $comment->reply_comment_id = $replyModel->reply_comment_id;
                        }
                    }
                }
            }
        }

        $this->writeEmailQueue($replyModel, $comment);

        $comment->content = $content;

    }

    /**
     * @param $replyModel ArticleComment
     * @param $comment ArticleComment
     * @throws \common\exceptions\DatabaseException
     */
    protected function writeEmailQueue($replyModel, $comment)
    {$this->layout = false;
        $mailTask = new TaskMail();
        // 先发给我, 再发给被回复人
        $mailTask->subject = sprintf("文章收到新的评论, 请即时查看");

        $contentParams = [
            'toOwner' => 1,
            'username' => Html::encode($comment->nickname),
            'replyContent' => preg_replace('/\[(@.*?(?=#\d+]))#(\d+)]/m', '', MyHtml::encode($comment->content)),
            'articleId' => $comment->article_id,
            'articleTitle' => $this->articleTitle,
        ];
        $mailTask->content = ($this->renderContentFilter($this->render('/template/replyEmailTpl', $contentParams)));
        //echo '<pre>';
        //print_r($mailTask->getAttributes());
        //die;
        $mailTask->is_html = TaskMail::IS_HTML_YES;
        $mailTask->to_mail = "shantongxu@qq.com";
        $mailTask->saveModel();

        if ($replyModel) {
            $pattern = '/\w[-\w.+]*@([A-Za-z0-9][-A-Za-z0-9]+\.)+[A-Za-z]{2,14}/';
            if (preg_match($pattern, $replyModel->email)) {
                $mailTask->id = null;
                $mailTask->subject = sprintf("回复: %s 回复了您的留言", $comment->nickname);
                $mailTask->isNewRecord = true;
                $mailTask->to_mail = $replyModel->email;
                $contentParams['toOwner'] = 0;

backend/views/article/comment.php
<?php
/**
 * Desc:
 * Created by PhpStorm.
 * User: xstnet
 * Date: 18-10-22
 * Time: 下午3:51
 */

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\helpers\Json;

$name = '评论';
?>
<?php $this->beginPage() ?>
	<!DOCTYPE html>
	<html lang="zh-CN">
	<head>
		<title><?= $name?>管理</title>
		<?= $this->render('../public/header.php')?>
		<?php $this->head() ?>
		<style>
			.title-image { cursor: pointer }
			.dialog-wrap { min-height: 200px; text-align: center }
			#showTitleImage img { max-width: 460px; max-height: 700px; }
			/*.layui-layer-page {width: auto !important;}*/
		</style>
	</head>
	<?php $this->beginBody() ?>
	<body class="body">
	<!-- 工具集 -->
	<div class="my-btn-box">
		<span class="fl">
			<a class="layui-btn btn-add btn-default" id="btn-read">全部已读</a>
	        <a class="layui-btn layui-btn-danger radius btn-delect" id="btn-delete-more">批量删除</a>
		</span>
			<span class="fr">
			<span class="layui-form-label">搜索条件：</span>
			<div class="layui-input-inline">
				<input type="text" autocomplete="off" placeholder="请输入搜索条件" class="layui-input">
			</div>
			<button class="layui-btn mgl-20">查询</button>
				<a class="layui-btn btn-add btn-default" id="btn-refresh"><i class="layui-icon layui-icon-refresh"></i></a>
		</span>
	</div>
	<span id="csrfToken"><?=Yii::$app->request->csrfToken?></span>

	<!-- 表格 -->
	<div id="dataTable" lay-filter="dataList"></div>

	<?= $this->render('../public/footer_js.php')?>
	<?= Html::jsFile('@static_backend/js/index.js')?>
	<script type="text/javascript">
		// 权限树
		var pageName = '<?= $name?>',
			layerIndex,
			rowId,
			rowObj;
		// layui方法
		layui.use(['table', 'form', 'layer', 'vip_table', 'util', 'vip_tab'], function () {
			// 操作对象
			var form = layui.form
				, table = layui.table
				, layer = layui.layer
				, vipTable = layui.vip_table
				, vipTab = layui.vip_tab
				, util = layui.util
				, $ = layui.jquery;

			// 表格渲染
			var tableIns = table.render({
				elem: '#dataTable'                  //指定原始表格元素选择器（推荐id选择器）
				//, height: vipTable.getFullHeight()    //容器高度
				, even: true
				, text: '暂无数据'
				, cols: [[
					{type:'checkbox'}
					, {field: 'id', title: 'ID', width: 80, align: 'center'}
					, {field: 'article_name', title: '名称', width: 255, align: 'center', templet: function (d) {
						var url = "<?=Yii::$app->userCache->get('setting')['site']['host']['value']?>/article-"+d.article_id+".html";
						return '<a style="color: #01AAED" target="_blank" href="'+ url +'">'+ d.article_name +'</a>';
						}}
					, {field: 'is_read', title: '状态', width: 80, templet: function (d) {
						var bg = d.is_delete == 1 ? '' : (d.is_read == 1 ? 'gray' : 'green');
						var text = d.is_delete == 1 ? '已删除' : (d.is_read == 1 ? '已读' : '未读');
						return '<span class="layui-badge layui-bg-'+ bg +'">'+ text +'</span>';
					}, align: 'center'}
					, {field: 'nickname', title: '评论人', width: 120, align: 'center'}
					, {field: 'email', title: '邮箱', width: 140, align: 'center'}
					, {field: 'content', title: '评论内容', /*width: 295,*/ align: 'center'}
					, {field: 'ip', title: 'IP', width: 120, align: 'center'}
					, {field: 'created_at', title: '评论时间', width: 145, templet: function (d) {return util.toDateString(d.created_at * 1000); }, align: 'center'}
					, {fixed: 'right', title: '操作', width: 80, align: 'center', toolbar: '#barOption'} //这里的toolbar值是模板元素的选择器
				]]
				, url: '<?=Yii::$app->urlManager->createUrl("article/get-comments")?>'
				, method: 'get'
				, page: true
				, limits: [10, 20, 30, 50, 100]
				, limit: 20 //默认采用20
				, size: 'sm' //小尺寸的表格
				, page: {
					layout: ['prev', 'page', 'next', 'skip', 'count', 'refresh','limit', ]
				}
				, loading: false
				, parseData: function (res) { //res 即为原始返回的数据
					return {
						"code": res.code, //解析接口状态
						"msg": res.message, //解析提示文本
						"count": res.data.total, //解析数据长度
						"data": res.data.list //解析数据列表
					};
				}
			});
			//监听事件 表格操作按钮
			table.on('tool(dataList)', function (obj) {
				rowObj = obj;
				console.log(obj.data);
				rowId = obj.data.id;
				var layEvent = obj.event; //获得 lay-event 对应的值（也可以是表头的 event 参数对应的值）
				if(layEvent === 'delete') { //删除
					actionDelete(obj);
				}
			});

			// 更改是否展示
			form.on('switch(filter-is-show)', function (data) {
				var elem = $(data.elem);
				$.post(
					'<?=Yii::$app->urlManager->createUrl("article/change-tag-status")?>',
					{id: elem.data('row_id')},
					function (result) {
						layer.msg(result.message);
						if (result.code !== AJAX_STATUS_SUCCESS) {
							elem.prop('checked', !data.elem.checked);
							form.render('checkbox') // 实现局部刷新，只刷新switch开关
						}
					}
				)
			});

			/**
			 * 删除
			 * @param obj
			 */
			function actionDelete(obj) {
				layer.confirm('确定删除这个评论吗？', function (index) {
					$.post(
						"<?=Yii::$app->urlManager->createUrl('article/delete-comments')?>",
						{ids: rowId},
						function (result) {
							layer.msg(result.message);
							if (result.code === AJAX_STATUS_SUCCESS) {
								tableIns.reload();
							}
						},
						'json',
					)
				});
			}
			
			/**
			 * 批量删除
			 */
			$('#btn-delete-more').click(function () {
				var checkData = table.checkStatus('dataTable');
				if (checkData.data.length <= 0) {
					layer.msg('请先选择要删除的数据');
					return false;
				}
				layer.confirm('确定删除选中的评论吗？', function (index) {
					var idArray = [];
					for (var i=0; i<checkData.data.length; i++) {
						idArray.push(checkData.data[ i ].id);
					}
//					var ids = idArray.join(',');
					$.post(
						'<?=Yii::$app->urlManager->createUrl("article/delete-comments")?>',
						{ids: idArray},
						function (result) {
							layer.msg(result.message, {time: 2000});
							if (result.code === AJAX_STATUS_SUCCESS) {
								tableIns.reload();
							}
						},
						'json'
					);
				});

//				console.log(checkData.data) //获取选中行的数据
//				console.log(checkData.data.length) //获取选中行数量，可作为是否有选中行的条件
//				console.log(checkData.isAll ) //表格是否全选
			});

			$('#btn-read').click(function () {
				$.post(
					'<?=Yii::$app->urlManager->createUrl("article/comment-read-all")?>',
					function (result) {
						layer.msg(result.message, {time: 2000});
						if (result.code === AJAX_STATUS_SUCCESS) {
							tableIns.reload();
						}
					},
					'json'
				);
			});
			
		});


	</script>
	<!-- 表格操作按钮集 -->
	<script type="text/html" id="barOption">
		<div class="layui-btn-group">
			<button class="layui-btn layui-btn-xs layui-btn-radius layui-btn-danger" lay-event="delete">删除</button>
		</div>
	</script>
	<?php $this->endBody() ?>
	</body>
	</html>
<?php $this->endPage() ?>